# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: drtaili <drtaili@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/24 20:51:40 by drtaili           #+#    #+#              #
#    Updated: 2023/02/27 01:06:36 by drtaili          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = draw.c ft_atof.c init.c julia.c main.c mandelbrot.c tool_fract.c keypress_needed_functions.c hooks.c tools2.c zoom.c errors_handler.c burningship.c julia_bonus.c mandelbrot_bonus.c 
SRC_bonus = burningship.c draw_bonus.c ft_atof.c init.c julia_bonus.c main_bonus.c mandelbrot_bonus.c tool_fract.c keypress_needed_functions.c hooks.c tools2.c zoom.c errors_handler.c julia.c mandelbrot.c
OBJS = $(SRC:.c=.o)
OBJS_bonus = $(SRC_bonus:.c=.o)
NAME = fractol
NAME_BONUS = fractol_bonus

CC = cc

RM = rm -rf

FLAGS = -Wall -Wextra -Werror

FLAGS_mlx = -lmlx -framework OpenGL -framework AppKit

all: $(NAME)

fractol : $(OBJS)
	$(CC) $(FLAGS) $(FLAGS_mlx) $(OBJS) -o $(NAME)

fractol_bonus : $(OBJS_bonus)
	$(CC) $(FLAGS) $(FLAGS_mlx) $(OBJS_bonus) -o $(NAME_BONUS)

%.o : %.c fractol.h
	$(CC) $(FLAGS) -c $< -o $@

clean:
	$(RM) $(OBJS) $(OBJS_bonus)

fclean: clean
	$(RM) $(NAME) $(NAME_BONUS)

re: fclean $(NAME) $(NAME_BONUS)

.PHONY = all clean fclean re
